/**
 * Production Source Registry seed (Sprint 2.2).
 * All URLs live here — services must not hardcode source URLs.
 * Fixture/offline runs inject payload via connector options.
 */

/**
 * @typedef {import('../registry/types.js').SourceRegistryEntry} SourceRegistryEntry
 */

/** @type {SourceRegistryEntry[]} */
export const PRODUCTION_SOURCES = Object.freeze([
  // --- Industrial Water ---
  Object.freeze({
    id: 'src_water_news_rss',
    name: 'Industrial Water News RSS',
    type: 'rss',
    country: 'GLOBAL',
    industry: 'industrial_water',
    vertical_pack: 'industrial_water',
    url: 'https://feeds.example-industrial.invalid/water/rss.xml',
    language: 'en',
    refresh_interval: '6h',
    enabled: true,
    priority: 10,
    supported_countries: ['GLOBAL', 'ES', 'AE', 'SA', 'US', 'MX'],
    supported_languages: ['en', 'es'],
    supported_vertical_packs: ['industrial_water'],
    parser: 'rss',
    normalizer: 'default',
    source_weight: 0.65,
    source_type: 'news',
  }),
  Object.freeze({
    id: 'src_water_permits_json',
    name: 'Water Permits JSON API',
    type: 'json_api',
    country: 'GLOBAL',
    industry: 'industrial_water',
    vertical_pack: 'industrial_water',
    url: 'https://api.example-industrial.invalid/permits/water',
    language: 'en',
    refresh_interval: '24h',
    enabled: true,
    priority: 20,
    supported_countries: ['GLOBAL', 'US', 'AE', 'ES'],
    supported_languages: ['en'],
    supported_vertical_packs: ['industrial_water'],
    parser: 'json_api',
    normalizer: 'default',
    source_weight: 0.9,
    source_type: 'environmental_permit',
  }),
  Object.freeze({
    id: 'src_water_csv_import',
    name: 'Water Projects CSV Import',
    type: 'csv',
    country: 'GLOBAL',
    industry: 'industrial_water',
    vertical_pack: 'industrial_water',
    url: 'file://imports/water-projects.csv',
    language: 'en',
    refresh_interval: 'manual',
    enabled: true,
    priority: 30,
    supported_countries: ['GLOBAL'],
    supported_languages: ['en', 'es'],
    supported_vertical_packs: ['industrial_water'],
    parser: 'csv',
    normalizer: 'default',
    source_weight: 0.7,
    source_type: 'manual_import',
  }),

  // --- Production Lines ---
  Object.freeze({
    id: 'src_lines_sitemap',
    name: 'Plant Construction Sitemap',
    type: 'sitemap',
    country: 'GLOBAL',
    industry: 'production_lines',
    vertical_pack: 'production_lines',
    url: 'https://www.example-industrial.invalid/plants/sitemap.xml',
    language: 'en',
    refresh_interval: '24h',
    enabled: true,
    priority: 15,
    supported_countries: ['GLOBAL', 'DE', 'MX', 'US'],
    supported_languages: ['en', 'de', 'es'],
    supported_vertical_packs: ['production_lines'],
    parser: 'sitemap',
    normalizer: 'default',
    source_weight: 0.7,
    source_type: 'construction_permit',
  }),
  Object.freeze({
    id: 'src_lines_news_rss',
    name: 'Production Lines News RSS',
    type: 'rss',
    country: 'GLOBAL',
    industry: 'production_lines',
    vertical_pack: 'production_lines',
    url: 'https://feeds.example-industrial.invalid/lines/rss.xml',
    language: 'en',
    refresh_interval: '12h',
    enabled: true,
    priority: 25,
    supported_countries: ['GLOBAL'],
    supported_languages: ['en'],
    supported_vertical_packs: ['production_lines'],
    parser: 'rss',
    normalizer: 'default',
    source_weight: 0.65,
    source_type: 'news',
  }),
  Object.freeze({
    id: 'src_lines_manual_url',
    name: 'Manual Plant Page URL',
    type: 'manual_url',
    country: 'GLOBAL',
    industry: 'production_lines',
    vertical_pack: 'production_lines',
    url: 'https://www.example-industrial.invalid/plants/expansion',
    language: 'en',
    refresh_interval: 'manual',
    enabled: true,
    priority: 40,
    supported_countries: ['GLOBAL'],
    supported_languages: ['en'],
    supported_vertical_packs: ['production_lines'],
    parser: 'html',
    normalizer: 'default',
    source_weight: 0.7,
    source_type: 'official_website',
  }),

  // --- Factory Automation ---
  Object.freeze({
    id: 'src_automation_json',
    name: 'Automation Grants JSON API',
    type: 'json_api',
    country: 'GLOBAL',
    industry: 'factory_automation',
    vertical_pack: 'factory_automation',
    url: 'https://api.example-industrial.invalid/automation/grants',
    language: 'en',
    refresh_interval: '24h',
    enabled: true,
    priority: 20,
    supported_countries: ['GLOBAL', 'DE', 'US', 'JP'],
    supported_languages: ['en', 'de', 'ja'],
    supported_vertical_packs: ['factory_automation'],
    parser: 'json_api',
    normalizer: 'default',
    source_weight: 0.8,
    source_type: 'investment_announcement',
  }),
  Object.freeze({
    id: 'src_automation_rss',
    name: 'Factory Automation RSS',
    type: 'rss',
    country: 'GLOBAL',
    industry: 'factory_automation',
    vertical_pack: 'factory_automation',
    url: 'https://feeds.example-industrial.invalid/automation/rss.xml',
    language: 'en',
    refresh_interval: '12h',
    enabled: true,
    priority: 25,
    supported_countries: ['GLOBAL'],
    supported_languages: ['en'],
    supported_vertical_packs: ['factory_automation'],
    parser: 'rss',
    normalizer: 'default',
    source_weight: 0.65,
    source_type: 'news',
  }),

  // --- Industrial Machinery ---
  Object.freeze({
    id: 'src_machinery_csv',
    name: 'Machinery RFQ CSV Import',
    type: 'csv',
    country: 'GLOBAL',
    industry: 'industrial_machinery',
    vertical_pack: 'industrial_machinery',
    url: 'file://imports/machinery-rfqs.csv',
    language: 'en',
    refresh_interval: 'manual',
    enabled: true,
    priority: 30,
    supported_countries: ['GLOBAL'],
    supported_languages: ['en'],
    supported_vertical_packs: ['industrial_machinery'],
    parser: 'csv',
    normalizer: 'default',
    source_weight: 0.7,
    source_type: 'manual_import',
  }),
  Object.freeze({
    id: 'src_machinery_json',
    name: 'Used Equipment JSON API',
    type: 'json_api',
    country: 'GLOBAL',
    industry: 'industrial_machinery',
    vertical_pack: 'industrial_machinery',
    url: 'https://api.example-industrial.invalid/machinery/listings',
    language: 'en',
    refresh_interval: '24h',
    enabled: true,
    priority: 35,
    supported_countries: ['GLOBAL'],
    supported_languages: ['en'],
    supported_vertical_packs: ['industrial_machinery'],
    parser: 'json_api',
    normalizer: 'default',
    source_weight: 0.55,
    source_type: 'trade',
  }),

  // --- Plastic Manufacturing ---
  Object.freeze({
    id: 'src_plastics_rss',
    name: 'Plastics Industry RSS',
    type: 'rss',
    country: 'GLOBAL',
    industry: 'plastic_manufacturing',
    vertical_pack: 'plastic_manufacturing',
    url: 'https://feeds.example-industrial.invalid/plastics/rss.xml',
    language: 'en',
    refresh_interval: '12h',
    enabled: true,
    priority: 20,
    supported_countries: ['GLOBAL', 'CN', 'MX', 'US', 'DE'],
    supported_languages: ['en', 'zh', 'es', 'de'],
    supported_vertical_packs: ['plastic_manufacturing'],
    parser: 'rss',
    normalizer: 'default',
    source_weight: 0.65,
    source_type: 'news',
  }),
  Object.freeze({
    id: 'src_plastics_pdf_meta',
    name: 'Trade Show PDF Metadata Upload',
    type: 'manual_pdf',
    country: 'GLOBAL',
    industry: 'plastic_manufacturing',
    vertical_pack: 'plastic_manufacturing',
    url: 'file://uploads/tradeshow-booth-list.pdf',
    language: 'en',
    refresh_interval: 'manual',
    enabled: true,
    priority: 45,
    supported_countries: ['GLOBAL'],
    supported_languages: ['en'],
    supported_vertical_packs: ['plastic_manufacturing'],
    parser: 'pdf_meta',
    normalizer: 'default',
    source_weight: 0.65,
    source_type: 'trade_show',
  }),
  Object.freeze({
    id: 'src_plastics_csv',
    name: 'Plastics OEM CSV Import',
    type: 'csv',
    country: 'GLOBAL',
    industry: 'plastic_manufacturing',
    vertical_pack: 'plastic_manufacturing',
    url: 'file://imports/plastics-oem.csv',
    language: 'en',
    refresh_interval: 'manual',
    enabled: true,
    priority: 30,
    supported_countries: ['GLOBAL'],
    supported_languages: ['en'],
    supported_vertical_packs: ['plastic_manufacturing'],
    parser: 'csv',
    normalizer: 'default',
    source_weight: 0.7,
    source_type: 'manual_import',
  }),
]);
